Add include guard
This prevents compilation errors caused by multiple #include directives for VoiceRecognitionV3.h:

In file included from C:\Users\per\AppData\Local\Temp\arduino_modified_sketch_736655\vr_sample_train.ino:30:0:

E:\electronics\arduino\libraries\VoiceRecognitionV3/VoiceRecognitionV3.h:106:7: error: redefinition of 'class VR'

 class VR : public SoftwareSerial{